DROP TABLE IF EXISTS "audit_logs";
DROP TABLE IF EXISTS "session";
DROP TABLE IF EXISTS "password";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "status";
DROP TABLE IF EXISTS "place";
DROP TABLE IF EXISTS "profile";
