version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    env_file:
      - .env
    volumes:
        - ./data/master:/var/lib/postgresql/data
    networks: 
      default:
        aliases: 
          - db_postgres
    expose:
      - 5432
  adminer:
    image: adminer:standalone
    restart: on-failure
    ports:
      - "8081:8080/tcp"
    networks:
      default:
        aliases:
          - adminer
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
    - "8080:8080"
networks: 
  default: