version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    volumes: 
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=userland
      - PGPORT=5432
    ports:
      - "5431:5432/tcp"
    networks: 
      default:
        aliases: 
          - db_userland
  redis:
    image: "redis:alpine"
    restart: on-failure
    command: redis-server
    ports:
      - "6378:6379/tcp"
    networks: 
      default:
        aliases: 
          - redis_userland
  adminer:
    image: adminer:standalone
    restart: on-failure
    ports:
      - "8081:8080/tcp"
    networks:
      default:
        aliases:
          - adminer
  userland:
    image: golang:1.17
    working_dir: /IH-Userland-Onboard
    volumes:
      - ./:/IH-Userland-Onboard:ro
    command: /bin/bash -c "go run ."
    ports:
      - "8080:8080/tcp"
    networks:
      default:
        aliases:
          - userland_service
networks: 
  default: