DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS tfa_codes;
DROP TABLE IF EXISTS tfa;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS password;
DROP TABLE IF EXISTS user;