DROP TABLE IF EXISTS "event";
DROP TABLE IF EXISTS "client";
DROP TABLE IF EXISTS "session";
DROP TABLE IF EXISTS "tfa_code";
DROP TABLE IF EXISTS "tfa";
DROP TABLE IF EXISTS "profile";
DROP TABLE IF EXISTS "password";
DROP TABLE IF EXISTS "user";